//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp._idb {

    public partial class HistorianLive {

        protected global::System.Web.UI.UpdatePanel UpdatePanel2;

        protected global::System.Web.UI.WebControls.DropDownList ddlFactory;

        protected global::System.Web.UI.WebControls.TextBox txtTagName;

        protected global::System.Web.UI.WebControls.TextBox txtQuality;

        protected global::System.Web.UI.WebControls.Button btnQuery;

        protected global::System.Web.UI.UpdatePanel UpdatePanel1;

        protected global::System.Web.UI.WebControls.GridView GridView1;

        protected global::WebApp._uc.ucPager ucPager;
    }
}
